title: Design After the End of the World
logo: /assets/img/Harrington,Margot_SolarEclipseKansasCity2017.jpg
description: "<strong>Margot Harrington<br/>Solar Eclipse, Kansas City 2017</strong><br/><br/>This collage (found and Japanese paper, fluorescent red sun, and gold leaf) was made in response to the eclipse to convey the delicate balance of the earth, the planets, and the passage of time. The eclipse was one of the few events in the last few years that brought thousands together, and it was because of science, not sports or politics. <a href='http://pitchdesignunion.com/'>View more of Margot Harrington’s work here</a>."
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
